name: jinsusbudget
description: Do not waste. Plan your daily budget.

publish_to: 'none'

version: 0.1.2+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.0.2
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env